//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TessOCR_Prototipo.EmailService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmailDto", Namespace="http://schemas.datacontract.org/2004/07/EmailDtoWrapper")]
    [System.SerializableAttribute()]
    public partial class EmailDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private TessOCR_Prototipo.EmailService.AttachmentDto Attachmentk__BackingFieldField;
        
        private string Bodyk__BackingFieldField;
        
        private string[] Cck__BackingFieldField;
        
        private bool IsHtmlk__BackingFieldField;
        
        private string Subjectk__BackingFieldField;
        
        private string[] Tok__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Attachment>k__BackingField", IsRequired=true)]
        public TessOCR_Prototipo.EmailService.AttachmentDto Attachmentk__BackingField {
            get {
                return this.Attachmentk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Attachmentk__BackingFieldField, value) != true)) {
                    this.Attachmentk__BackingFieldField = value;
                    this.RaisePropertyChanged("Attachmentk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Body>k__BackingField", IsRequired=true)]
        public string Bodyk__BackingField {
            get {
                return this.Bodyk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Bodyk__BackingFieldField, value) != true)) {
                    this.Bodyk__BackingFieldField = value;
                    this.RaisePropertyChanged("Bodyk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Cc>k__BackingField", IsRequired=true)]
        public string[] Cck__BackingField {
            get {
                return this.Cck__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Cck__BackingFieldField, value) != true)) {
                    this.Cck__BackingFieldField = value;
                    this.RaisePropertyChanged("Cck__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<IsHtml>k__BackingField", IsRequired=true)]
        public bool IsHtmlk__BackingField {
            get {
                return this.IsHtmlk__BackingFieldField;
            }
            set {
                if ((this.IsHtmlk__BackingFieldField.Equals(value) != true)) {
                    this.IsHtmlk__BackingFieldField = value;
                    this.RaisePropertyChanged("IsHtmlk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Subject>k__BackingField", IsRequired=true)]
        public string Subjectk__BackingField {
            get {
                return this.Subjectk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Subjectk__BackingFieldField, value) != true)) {
                    this.Subjectk__BackingFieldField = value;
                    this.RaisePropertyChanged("Subjectk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<To>k__BackingField", IsRequired=true)]
        public string[] Tok__BackingField {
            get {
                return this.Tok__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Tok__BackingFieldField, value) != true)) {
                    this.Tok__BackingFieldField = value;
                    this.RaisePropertyChanged("Tok__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttachmentDto", Namespace="http://schemas.datacontract.org/2004/07/EmailDtoWrapper")]
    [System.SerializableAttribute()]
    public partial class AttachmentDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private byte[] _contentField;
        
        private string _filenameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte[] _content {
            get {
                return this._contentField;
            }
            set {
                if ((object.ReferenceEquals(this._contentField, value) != true)) {
                    this._contentField = value;
                    this.RaisePropertyChanged("_content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _filename {
            get {
                return this._filenameField;
            }
            set {
                if ((object.ReferenceEquals(this._filenameField, value) != true)) {
                    this._filenameField = value;
                    this.RaisePropertyChanged("_filename");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmailService.IEmailService")]
    public interface IEmailService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailService/SendEmail", ReplyAction="http://tempuri.org/IEmailService/SendEmailResponse")]
        void SendEmail(string applicationName, TessOCR_Prototipo.EmailService.EmailDto emailData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailService/SendEmail", ReplyAction="http://tempuri.org/IEmailService/SendEmailResponse")]
        System.Threading.Tasks.Task SendEmailAsync(string applicationName, TessOCR_Prototipo.EmailService.EmailDto emailData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmailServiceChannel : TessOCR_Prototipo.EmailService.IEmailService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmailServiceClient : System.ServiceModel.ClientBase<TessOCR_Prototipo.EmailService.IEmailService>, TessOCR_Prototipo.EmailService.IEmailService {
        
        public EmailServiceClient() {
        }
        
        public EmailServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmailServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SendEmail(string applicationName, TessOCR_Prototipo.EmailService.EmailDto emailData) {
            base.Channel.SendEmail(applicationName, emailData);
        }
        
        public System.Threading.Tasks.Task SendEmailAsync(string applicationName, TessOCR_Prototipo.EmailService.EmailDto emailData) {
            return base.Channel.SendEmailAsync(applicationName, emailData);
        }
    }
}
